In [1]:
import pandas as pd
#pd.set_option('display.max_columns', None)
#pd.set_option('display.max_rows', None)

In [2]:
df = pd.read_csv("ocorrencia_2010_2020.csv", sep=';', parse_dates=['ocorrencia_dia'], dayfirst=True)
df.head(5)

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,40211,40211,40211,40211,40211,INCIDENTE,***,***,RIO DE JANEIRO,RJ,...,2010-01-03,12:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
1,40349,40349,40349,40349,40349,INCIDENTE,NaN,NaN,BELÉM,PA,...,2010-01-03,11:05:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
2,40351,40351,40351,40351,40351,INCIDENTE,NaN,NaN,RIO DE JANEIRO,RJ,...,2010-01-03,03:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
3,39527,39527,39527,39527,39527,ACIDENTE,-13.1066666667,-55.9930555556,LUCAS DO RIO VERDE,MT,...,2010-01-04,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,0,1,NÃO
4,40324,40324,40324,40324,40324,INCIDENTE,NaN,NaN,PELOTAS,RS,...,2010-01-05,19:25:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO

Localizar na Linha 1  e coluna (ocorrencia_cidade )

In [3]:
df.loc[1, 'ocorrencia_cidade']

'BELÉM'

PEGAR OS DADOS DE TODA UMA LINHA, POR EXEMPLO LINHA 3
def.loc[indice da linha]

In [4]:
df.loc[3]

codigo_ocorrencia                               39527
codigo_ocorrencia1                              39527
codigo_ocorrencia2                              39527
codigo_ocorrencia3                              39527
codigo_ocorrencia4                              39527
ocorrencia_classificacao                     ACIDENTE
ocorrencia_latitude                    -13.1066666667
ocorrencia_longitude                   -55.9930555556
ocorrencia_cidade                  LUCAS DO RIO VERDE
ocorrencia_uf                                      MT
ocorrencia_pais                                BRASIL
ocorrencia_aerodromo                             ****
ocorrencia_dia                    2010-01-04 00:00:00
ocorrencia_hora                              17:30:00
investigacao_aeronave_liberada                    SIM
investigacao_status                        FINALIZADA
divulgacao_relatorio_numero         A-539/CENIPA/2018
divulgacao_relatorio_publicado                    SIM
divulgacao_dia_publicacao                  2019-10-28
total_recomendacoes                                 0
total_aeronaves_envolvidas                          1
ocorrencia_saida_pista                            NÃO
Name: 3, dtype: object

PEGAR OS DADOS DA LINHA1 ATÉ A LINHA 3

In [5]:
df.loc[1:3]

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
1,40349,40349,40349,40349,40349,INCIDENTE,NaN,NaN,BELÉM,PA,...,2010-01-03,11:05:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
2,40351,40351,40351,40351,40351,INCIDENTE,NaN,NaN,RIO DE JANEIRO,RJ,...,2010-01-03,03:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
3,39527,39527,39527,39527,39527,ACIDENTE,-13.1066666667,-55.9930555556,LUCAS DO RIO VERDE,MT,...,2010-01-04,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,0,1,NÃO

TRAZER DADOS DA LINHA 10 E 40 (sem informar a coluna)

In [6]:
df.loc[[10,40]]

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
10,39789,39789,39789,39789,39789,INCIDENTE,NaN,NaN,SÃO PEDRO DO SUL,RS,...,2010-01-10,21:30:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO
40,39158,39158,39158,39158,39158,INCIDENTE,***,***,BELÉM,PA,...,2010-01-28,16:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO

PEGAR TODOS OS DADOS DA COLUNA SEM INFORMA AS LINHAS
df.loc[:, Nome da Coluna]

In [7]:
df.loc[:,'ocorrencia_cidade']

0           RIO DE JANEIRO
1                    BELÉM
2           RIO DE JANEIRO
3       LUCAS DO RIO VERDE
4                  PELOTAS
               ...
5747              CAMPINAS
5748     LAGOA DA CONFUSÃO
5749        RIO DE JANEIRO
5750             VICENTINA
5751        RIO DE JANEIRO
Name: ocorrencia_cidade, Length: 5752, dtype: object

REALIZANDO A LIMPEZA DOS DADOS - PARTE 2

VRIFICAR SE O CAMPO TEM VALORES ÚNICOS PARA LINHAS DIFERENTES

In [8]:
df.codigo_ocorrencia.is_unique

True

Como é unico vou utilizá-lo como índice no DataFrame, no código abaixo não atualizo o DataFrame
Não fiz alteração no DataFrame

In [9]:
df.set_index('codigo_ocorrencia')

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
codigo_ocorrencia,,,,,,,,,,,,,,,,,,,,,
40211,40211,40211,40211,40211,INCIDENTE,***,***,RIO DE JANEIRO,RJ,BRASIL,...,2010-01-03,12:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
40349,40349,40349,40349,40349,INCIDENTE,NaN,NaN,BELÉM,PA,BRASIL,...,2010-01-03,11:05:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
40351,40351,40351,40351,40351,INCIDENTE,NaN,NaN,RIO DE JANEIRO,RJ,BRASIL,...,2010-01-03,03:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
39527,39527,39527,39527,39527,ACIDENTE,-13.1066666667,-55.9930555556,LUCAS DO RIO VERDE,MT,BRASIL,...,2010-01-04,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,0,1,NÃO
40324,40324,40324,40324,40324,INCIDENTE,NaN,NaN,PELOTAS,RS,BRASIL,...,2010-01-05,19:25:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79804,79804,79804,79804,79804,INCIDENTE,-23.0069444444,-47.1344444444,CAMPINAS,SP,BRASIL,...,2020-12-29,19:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
79757,79757,79757,79757,79757,INCIDENTE GRAVE,-10.804722,-49.756389,LAGOA DA CONFUSÃO,TO,BRASIL,...,2020-12-30,18:30:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
79802,79802,79802,79802,79802,INCIDENTE,-22.81,-43.25055555555,RIO DE JANEIRO,RJ,BRASIL,...,2020-12-30,00:54:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
79756,79756,79756,79756,79756,INCIDENTE GRAVE,-22.507222,-54.364167,VICENTINA,MS,BRASIL,...,2020-12-31,09:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
79844,79844,79844,79844,79844,INCIDENTE,"-22,9875","-43,37",RIO DE JANEIRO,RJ,BRASIL,...,2020-12-31,13:24:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO

PARA FAZER A ALTERAÇÃO NO DataFrame

In [10]:
df.set_index('codigo_ocorrencia', inplace=True)

AGORA TENHO "codigo_ocorrencia" COMO ÍNDICE DO DataFrame

In [11]:
df.head()

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
codigo_ocorrencia,,,,,,,,,,,,,,,,,,,,,
40211,40211,40211,40211,40211,INCIDENTE,***,***,RIO DE JANEIRO,RJ,BRASIL,...,2010-01-03,12:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
40349,40349,40349,40349,40349,INCIDENTE,NaN,NaN,BELÉM,PA,BRASIL,...,2010-01-03,11:05:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
40351,40351,40351,40351,40351,INCIDENTE,NaN,NaN,RIO DE JANEIRO,RJ,BRASIL,...,2010-01-03,03:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
39527,39527,39527,39527,39527,ACIDENTE,-13.1066666667,-55.9930555556,LUCAS DO RIO VERDE,MT,BRASIL,...,2010-01-04,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,0,1,NÃO
40324,40324,40324,40324,40324,INCIDENTE,NaN,NaN,PELOTAS,RS,BRASIL,...,2010-01-05,19:25:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO

AGORA PARA OBTER OS DADOS, TENHO QUE USAR ESSE ÍNDICE NO DataFrame

In [12]:
# Retorna todos os dados dessa linha referente ao índice ou label 40349
df.loc[40349]

codigo_ocorrencia1                              40349
codigo_ocorrencia2                              40349
codigo_ocorrencia3                              40349
codigo_ocorrencia4                              40349
ocorrencia_classificacao                    INCIDENTE
ocorrencia_latitude                               NaN
ocorrencia_longitude                              NaN
ocorrencia_cidade                               BELÉM
ocorrencia_uf                                      PA
ocorrencia_pais                                BRASIL
ocorrencia_aerodromo                             SBBE
ocorrencia_dia                    2010-01-03 00:00:00
ocorrencia_hora                              11:05:00
investigacao_aeronave_liberada                    SIM
investigacao_status                        FINALIZADA
divulgacao_relatorio_numero                       NaN
divulgacao_relatorio_publicado                    NÃO
divulgacao_dia_publicacao                         NaN
total_recomendacoes                                 0
total_aeronaves_envolvidas                          1
ocorrencia_saida_pista                            NÃO
Name: 40349, dtype: object

REMOVER O ÍNDICE DO DataFrame, VOLTAR AO ORIGINAL

In [13]:
df.reset_index(drop=True, inplace=True)

In [14]:
df.head()

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,40211,40211,40211,40211,INCIDENTE,***,***,RIO DE JANEIRO,RJ,BRASIL,...,2010-01-03,12:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
1,40349,40349,40349,40349,INCIDENTE,NaN,NaN,BELÉM,PA,BRASIL,...,2010-01-03,11:05:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
2,40351,40351,40351,40351,INCIDENTE,NaN,NaN,RIO DE JANEIRO,RJ,BRASIL,...,2010-01-03,03:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
3,39527,39527,39527,39527,ACIDENTE,-13.1066666667,-55.9930555556,LUCAS DO RIO VERDE,MT,BRASIL,...,2010-01-04,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,0,1,NÃO
4,40324,40324,40324,40324,INCIDENTE,NaN,NaN,PELOTAS,RS,BRASIL,...,2010-01-05,19:25:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO

COMO ALTERAR OS DADOS DO campo "ocorrencia_aerodromo"

In [15]:
df.ocorrencia_aerodromo

0       ****
1       SBBE
2       SBRJ
3       ****
4       SBPK
        ...
5747    SBKP
5748    ****
5749    SBGL
5750    ****
5751    SBJR
Name: ocorrencia_aerodromo, Length: 5752, dtype: object

PASSAR CONTEÚDO Do ÍNDICE 0 CAMPO "ocorrencia_aerodromo" PARA VAZIO

In [16]:
df.loc[0,"ocorrencia_aerodromo"] = ''

In [17]:
df.ocorrencia_aerodromo

0
1       SBBE
2       SBRJ
3       ****
4       SBPK
        ...
5747    SBKP
5748    ****
5749    SBGL
5750    ****
5751    SBJR
Name: ocorrencia_aerodromo, Length: 5752, dtype: object

ALTERAR TODOS OS DADOS DE UMA LINHA - Não faz muito sentido
TODOS OS DADOS DA LINHA 1

In [18]:
df.loc[1] = 20

In [19]:
df.head(2)

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,40211,40211,40211,40211,INCIDENTE,***,***,RIO DE JANEIRO,RJ,BRASIL,...,2010-01-03 00:00:00,12:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
1,20,20,20,20,20,20,20,20,20,20,...,20,20,20,20,20,20,20,20,20,20

ALTERAR O DADO DE TODAS AS LINHA DE UMA COLUNA
Exemplo: total_recomendacoes - ALTERAR PARA 10

In [20]:
df.loc[:,'total_recomendacoes'] = 10

In [21]:
df.total_recomendacoes

0       10
1       10
2       10
3       10
4       10
        ..
5747    10
5748    10
5749    10
5750    10
5751    10
Name: total_recomendacoes, Length: 5752, dtype: int64

FAZENDO O BACKUP DE UMA COLUNA, CRIA NA ULTIMA POSICAO A COLUNA CRIADA

In [22]:
df['ocorrencia_uf_bkp'] = df.ocorrencia_uf

In [23]:
df

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista,ocorrencia_uf_bkp
0,40211,40211,40211,40211,INCIDENTE,***,***,RIO DE JANEIRO,RJ,BRASIL,...,12:00:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO,RJ
1,20,20,20,20,20,20,20,20,20,20,...,20,20,20,20,20,20,10,20,20,20
2,40351,40351,40351,40351,INCIDENTE,NaN,NaN,RIO DE JANEIRO,RJ,BRASIL,...,03:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,10,1,NÃO,RJ
3,39527,39527,39527,39527,ACIDENTE,-13.1066666667,-55.9930555556,LUCAS DO RIO VERDE,MT,BRASIL,...,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,10,1,NÃO,MT
4,40324,40324,40324,40324,INCIDENTE,NaN,NaN,PELOTAS,RS,BRASIL,...,19:25:00,SIM,FINALIZADA,NaN,NÃO,NaN,10,1,NÃO,RS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5747,79804,79804,79804,79804,INCIDENTE,-23.0069444444,-47.1344444444,CAMPINAS,SP,BRASIL,...,19:00:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO,SP
5748,79757,79757,79757,79757,INCIDENTE GRAVE,-10.804722,-49.756389,LAGOA DA CONFUSÃO,TO,BRASIL,...,18:30:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO,TO
5749,79802,79802,79802,79802,INCIDENTE,-22.81,-43.25055555555,RIO DE JANEIRO,RJ,BRASIL,...,00:54:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO,RJ
5750,79756,79756,79756,79756,INCIDENTE GRAVE,-22.507222,-54.364167,VICENTINA,MS,BRASIL,...,09:00:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO,MS
5751,79844,79844,79844,79844,INCIDENTE,"-22,9875","-43,37",RIO DE JANEIRO,RJ,BRASIL,...,13:24:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO,RJ

ALTERAR CONTEÚDO DA COLUNA ocorrencia_classificacao ONDE A COLUNA ocorrencia_uf = SP  PARA "GRAVE"

In [25]:
df.loc[df.ocorrencia_uf == 'SP', ['ocorrencia_classificacao']] = 'GRAVE'

TODOS DA ocorrecia_uf = 'SP' FORAM ALTERADOS PARA 'GRAVE' 
LISTANDO APENAS OS CAMPOS ocorrencia_uf E ocorrencia_classificacao

In [26]:
df.loc[df.ocorrencia_uf == 'SP', ['ocorrencia_uf', 'ocorrencia_classificacao']]

     ocorrencia_uf ocorrencia_classificacao
11              SP                    GRAVE
16              SP                    GRAVE
18              SP                    GRAVE
26              SP                    GRAVE
27              SP                    GRAVE
...            ...                      ...
5704            SP                    GRAVE
5705            SP                    GRAVE
5715            SP                    GRAVE
5742            SP                    GRAVE
5747            SP                    GRAVE

[1373 rows x 2 columns]

VOLTAR O DATAFRAME AO ESTADO ORIGINAL

In [27]:
df = pd.read_csv("ocorrencia_2010_2020.csv", sep=';', parse_dates=['ocorrencia_dia'], dayfirst=True)
df.head()

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,40211,40211,40211,40211,40211,INCIDENTE,***,***,RIO DE JANEIRO,RJ,...,2010-01-03,12:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
1,40349,40349,40349,40349,40349,INCIDENTE,NaN,NaN,BELÉM,PA,...,2010-01-03,11:05:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
2,40351,40351,40351,40351,40351,INCIDENTE,NaN,NaN,RIO DE JANEIRO,RJ,...,2010-01-03,03:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
3,39527,39527,39527,39527,39527,ACIDENTE,-13.1066666667,-55.9930555556,LUCAS DO RIO VERDE,MT,...,2010-01-04,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,0,1,NÃO
4,40324,40324,40324,40324,40324,INCIDENTE,NaN,NaN,PELOTAS,RS,...,2010-01-05,19:25:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO

EFETUAR A LIMPEZA - LIMPAR OS DADOS NÃO INF0RMADOS 
ocorrencia_uf
**
ocorrencia_aerodromo
****
*****
####

LIMPAR TODAS LINHAS QUE TEM **
NA -not available - atribuir valores que não estão disponíveis na célula

In [28]:
df.loc[df.ocorrencia_aerodromo == '****', ['ocorrencia_aerodromo']] = pd.NA

In [29]:
pd.set_option('display.max_columns', None)

In [30]:
df.head(5)

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,40211,40211,40211,40211,40211,INCIDENTE,***,***,RIO DE JANEIRO,RJ,BRASIL,<NA>,2010-01-03,12:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
1,40349,40349,40349,40349,40349,INCIDENTE,NaN,NaN,BELÉM,PA,BRASIL,SBBE,2010-01-03,11:05:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
2,40351,40351,40351,40351,40351,INCIDENTE,NaN,NaN,RIO DE JANEIRO,RJ,BRASIL,SBRJ,2010-01-03,03:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
3,39527,39527,39527,39527,39527,ACIDENTE,-13.1066666667,-55.9930555556,LUCAS DO RIO VERDE,MT,BRASIL,<NA>,2010-01-04,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,0,1,NÃO
4,40324,40324,40324,40324,40324,INCIDENTE,NaN,NaN,PELOTAS,RS,BRASIL,SBPK,2010-01-05,19:25:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO

FUNÇÃO:  replace - FAZER TODAS MODIFICAÇÕES DE UMA VEZ
df.replace(['**', '*****','NULL']

In [31]:
df.replace(['**','***', '*****','NULL'], pd.NA, inplace = True)

In [32]:
df.head(5)

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,40211,40211,40211,40211,40211,INCIDENTE,<NA>,<NA>,RIO DE JANEIRO,RJ,BRASIL,<NA>,2010-01-03,12:00:00,SIM,FINALIZADA,<NA>,NÃO,NaN,0,1,NÃO
1,40349,40349,40349,40349,40349,INCIDENTE,NaN,NaN,BELÉM,PA,BRASIL,SBBE,2010-01-03,11:05:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
2,40351,40351,40351,40351,40351,INCIDENTE,NaN,NaN,RIO DE JANEIRO,RJ,BRASIL,SBRJ,2010-01-03,03:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
3,39527,39527,39527,39527,39527,ACIDENTE,-13.1066666667,-55.9930555556,LUCAS DO RIO VERDE,MT,BRASIL,<NA>,2010-01-04,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,0,1,NÃO
4,40324,40324,40324,40324,40324,INCIDENTE,NaN,NaN,PELOTAS,RS,BRASIL,SBPK,2010-01-05,19:25:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO

In [33]:
df.tail()

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
5747,79804,79804,79804,79804,79804,INCIDENTE,-23.0069444444,-47.1344444444,CAMPINAS,SP,BRASIL,SBKP,2020-12-29,19:00:00,SIM,FINALIZADA,<NA>,NÃO,NaN,0,1,NÃO
5748,79757,79757,79757,79757,79757,INCIDENTE GRAVE,-10.804722,-49.756389,LAGOA DA CONFUSÃO,TO,BRASIL,<NA>,2020-12-30,18:30:00,SIM,FINALIZADA,<NA>,NÃO,NaN,0,1,NÃO
5749,79802,79802,79802,79802,79802,INCIDENTE,-22.81,-43.25055555555,RIO DE JANEIRO,RJ,BRASIL,SBGL,2020-12-30,00:54:00,SIM,FINALIZADA,<NA>,NÃO,NaN,0,1,NÃO
5750,79756,79756,79756,79756,79756,INCIDENTE GRAVE,-22.507222,-54.364167,VICENTINA,MS,BRASIL,<NA>,2020-12-31,09:00:00,SIM,FINALIZADA,<NA>,NÃO,NaN,0,1,NÃO
5751,79844,79844,79844,79844,79844,INCIDENTE,"-22,9875","-43,37",RIO DE JANEIRO,RJ,BRASIL,SBJR,2020-12-31,13:24:00,SIM,FINALIZADA,<NA>,NÃO,NaN,0,1,NÃO

QUANTOS (NAs - Não Informado) TENHO NO DATAFRAME
DADO NÃO INFORMADO: retorna True
Função: isna() e isnull()

In [34]:
df.isna().head(5)

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,False,False,False,False,False,False,True,True,False,False,False,True,False,False,False,False,True,False,True,False,False,False
1,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,True,False,False,False
2,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,True,False,False,False

In [35]:
df.isna().sum()

codigo_ocorrencia                    0
codigo_ocorrencia1                   0
codigo_ocorrencia2                   0
codigo_ocorrencia3                   0
codigo_ocorrencia4                   0
ocorrencia_classificacao             0
ocorrencia_latitude               2293
ocorrencia_longitude              2295
ocorrencia_cidade                    0
ocorrencia_uf                        1
ocorrencia_pais                      0
ocorrencia_aerodromo              2331
ocorrencia_dia                       0
ocorrencia_hora                      1
investigacao_aeronave_liberada    2482
investigacao_status                340
divulgacao_relatorio_numero       3800
divulgacao_relatorio_publicado       0
divulgacao_dia_publicacao         4258
total_recomendacoes                  0
total_aeronaves_envolvidas           0
ocorrencia_saida_pista               0
dtype: int64

In [36]:
df.isnull().head(5)

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,False,False,False,False,False,False,True,True,False,False,False,True,False,False,False,False,True,False,True,False,False,False
1,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,True,False,False,False
2,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,True,False,False,False

In [37]:
df.isnull().sum()

codigo_ocorrencia                    0
codigo_ocorrencia1                   0
codigo_ocorrencia2                   0
codigo_ocorrencia3                   0
codigo_ocorrencia4                   0
ocorrencia_classificacao             0
ocorrencia_latitude               2293
ocorrencia_longitude              2295
ocorrencia_cidade                    0
ocorrencia_uf                        1
ocorrencia_pais                      0
ocorrencia_aerodromo              2331
ocorrencia_dia                       0
ocorrencia_hora                      1
investigacao_aeronave_liberada    2482
investigacao_status                340
divulgacao_relatorio_numero       3800
divulgacao_relatorio_publicado       0
divulgacao_dia_publicacao         4258
total_recomendacoes                  0
total_aeronaves_envolvidas           0
ocorrencia_saida_pista               0
dtype: int64

COLOCAR VALORES NOS DADOS NÃO INFORMADOS
COLOCAR VALOR (10) EM TODOS OS DADOS NÃO INFORMADOS 
*** MUDA APENAS EM TEMPO DE VISUALIZAÇÃO ***
**** PARA SALVAR AS ALTERAÇÕES ****
inplace=True

In [38]:
df.fillna(10, inplace=True)

NÃO RETORNA NENHUM COM VALO (NA)

In [39]:
df.isnull().sum()

codigo_ocorrencia                 0
codigo_ocorrencia1                0
codigo_ocorrencia2                0
codigo_ocorrencia3                0
codigo_ocorrencia4                0
ocorrencia_classificacao          0
ocorrencia_latitude               0
ocorrencia_longitude              0
ocorrencia_cidade                 0
ocorrencia_uf                     0
ocorrencia_pais                   0
ocorrencia_aerodromo              0
ocorrencia_dia                    0
ocorrencia_hora                   0
investigacao_aeronave_liberada    0
investigacao_status               0
divulgacao_relatorio_numero       0
divulgacao_relatorio_publicado    0
divulgacao_dia_publicacao         0
total_recomendacoes               0
total_aeronaves_envolvidas        0
ocorrencia_saida_pista            0
dtype: int64

In [40]:
df.head()

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,40211,40211,40211,40211,40211,INCIDENTE,10,10,RIO DE JANEIRO,RJ,BRASIL,10,2010-01-03,12:00:00,SIM,FINALIZADA,10,NÃO,10,0,1,NÃO
1,40349,40349,40349,40349,40349,INCIDENTE,10,10,BELÉM,PA,BRASIL,SBBE,2010-01-03,11:05:00,SIM,FINALIZADA,10,NÃO,10,0,1,NÃO
2,40351,40351,40351,40351,40351,INCIDENTE,10,10,RIO DE JANEIRO,RJ,BRASIL,SBRJ,2010-01-03,03:00:00,SIM,FINALIZADA,10,NÃO,10,0,1,NÃO
3,39527,39527,39527,39527,39527,ACIDENTE,-13.1066666667,-55.9930555556,LUCAS DO RIO VERDE,MT,BRASIL,10,2010-01-04,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,0,1,NÃO
4,40324,40324,40324,40324,40324,INCIDENTE,10,10,PELOTAS,RS,BRASIL,SBPK,2010-01-05,19:25:00,SIM,FINALIZADA,10,NÃO,10,0,1,NÃO

PEGAR TODOS CAMPOS COM VALOR (10) SUBSTITUIR POR (NA)

In [41]:
df.replace([10], pd.NA, inplace=True)

In [42]:
df.isnull().sum()

codigo_ocorrencia                    0
codigo_ocorrencia1                   0
codigo_ocorrencia2                   0
codigo_ocorrencia3                   0
codigo_ocorrencia4                   0
ocorrencia_classificacao             0
ocorrencia_latitude               2293
ocorrencia_longitude              2295
ocorrencia_cidade                    0
ocorrencia_uf                        1
ocorrencia_pais                      0
ocorrencia_aerodromo              2331
ocorrencia_dia                       0
ocorrencia_hora                      1
investigacao_aeronave_liberada    2482
investigacao_status                340
divulgacao_relatorio_numero       3800
divulgacao_relatorio_publicado       0
divulgacao_dia_publicacao         4258
total_recomendacoes                  2
total_aeronaves_envolvidas           0
ocorrencia_saida_pista               0
dtype: int64

ALTERAR ALGUNS LOCAIS QUE TENHA (NA) PARA O VALOR (10)

In [43]:
df.fillna(value={'total_recomendacoes':10}, inplace=True)

total_recomendacoes voltou a ficar (0)

In [46]:
df.isnull().sum()

codigo_ocorrencia                    0
codigo_ocorrencia1                   0
codigo_ocorrencia2                   0
codigo_ocorrencia3                   0
codigo_ocorrencia4                   0
ocorrencia_classificacao             0
ocorrencia_latitude               2293
ocorrencia_longitude              2295
ocorrencia_cidade                    0
ocorrencia_uf                        1
ocorrencia_pais                      0
ocorrencia_aerodromo              2331
ocorrencia_dia                       0
ocorrencia_hora                      1
investigacao_aeronave_liberada    2482
investigacao_status                340
divulgacao_relatorio_numero       3800
divulgacao_relatorio_publicado       0
divulgacao_dia_publicacao         4258
total_recomendacoes                  0
total_aeronaves_envolvidas           0
ocorrencia_saida_pista               0
dtype: int64

REALIZANDO A LIMPEZA DE DADOS - PARTE 4

CRIAR UMA COLUNA (total_recomendacoes_bkp) RECEBENDO DADOS DE (total_recomendacoes)

In [47]:
df['total_recomendacoes_bkp'] = df.total_recomendacoes

In [48]:
df.head()

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista,total_recomendacoes_bkp
0,40211,40211,40211,40211,40211,INCIDENTE,<NA>,<NA>,RIO DE JANEIRO,RJ,BRASIL,<NA>,2010-01-03,12:00:00,SIM,FINALIZADA,<NA>,NÃO,<NA>,0,1,NÃO,0
1,40349,40349,40349,40349,40349,INCIDENTE,<NA>,<NA>,BELÉM,PA,BRASIL,SBBE,2010-01-03,11:05:00,SIM,FINALIZADA,<NA>,NÃO,<NA>,0,1,NÃO,0
2,40351,40351,40351,40351,40351,INCIDENTE,<NA>,<NA>,RIO DE JANEIRO,RJ,BRASIL,SBRJ,2010-01-03,03:00:00,SIM,FINALIZADA,<NA>,NÃO,<NA>,0,1,NÃO,0
3,39527,39527,39527,39527,39527,ACIDENTE,-13.1066666667,-55.9930555556,LUCAS DO RIO VERDE,MT,BRASIL,<NA>,2010-01-04,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,0,1,NÃO,0
4,40324,40324,40324,40324,40324,INCIDENTE,<NA>,<NA>,PELOTAS,RS,BRASIL,SBPK,2010-01-05,19:25:00,SIM,FINALIZADA,<NA>,NÃO,<NA>,0,1,NÃO,0

EXCLUIR COLUNA (total_recomendacoes_bkp)
DARÁ ERRO, POR PADRÃO TENTA APAGAR A LINHA.
POR PADRÃO O EIXO = 0 ( COLUNA )
PARA PODER APAGAR MUDAR O (eixo) para 1 ( LINHA )

In [49]:
df.drop(['total_recomendacoes_bkp'])

KeyError: "['total_recomendacoes_bkp'] not found in axis"

In [50]:
PARA PODER APAGAR MUDAR O (eixo) para 1 ( LINHA )
inplace=True -- Atualizar o DataFrame
A coluna (total_recomendacoes_bkp) será excluída

SyntaxError: invalid syntax (Temp/ipykernel_9384/3365894994.py, line 1)

In [51]:
df.drop(['total_recomendacoes_bkp'], axis=1, inplace=True)

EXCLUI TODAS AS LINHAS COM CAMPOS (NA) 
****** NÃO USAR ********

In [52]:
# df.dropna()

EXCLUI AS LINHAS CAMPOS COM (NA) ESPECIFICANDO A COLUNA

In [53]:
# df.dropna(subset=['ocorrencia_uf'])

In [54]:
df

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,40211,40211,40211,40211,40211,INCIDENTE,<NA>,<NA>,RIO DE JANEIRO,RJ,BRASIL,<NA>,2010-01-03,12:00:00,SIM,FINALIZADA,<NA>,NÃO,<NA>,0,1,NÃO
1,40349,40349,40349,40349,40349,INCIDENTE,<NA>,<NA>,BELÉM,PA,BRASIL,SBBE,2010-01-03,11:05:00,SIM,FINALIZADA,<NA>,NÃO,<NA>,0,1,NÃO
2,40351,40351,40351,40351,40351,INCIDENTE,<NA>,<NA>,RIO DE JANEIRO,RJ,BRASIL,SBRJ,2010-01-03,03:00:00,SIM,FINALIZADA,<NA>,NÃO,<NA>,0,1,NÃO
3,39527,39527,39527,39527,39527,ACIDENTE,-13.1066666667,-55.9930555556,LUCAS DO RIO VERDE,MT,BRASIL,<NA>,2010-01-04,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,0,1,NÃO
4,40324,40324,40324,40324,40324,INCIDENTE,<NA>,<NA>,PELOTAS,RS,BRASIL,SBPK,2010-01-05,19:25:00,SIM,FINALIZADA,<NA>,NÃO,<NA>,0,1,NÃO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5747,79804,79804,79804,79804,79804,INCIDENTE,-23.0069444444,-47.1344444444,CAMPINAS,SP,BRASIL,SBKP,2020-12-29,19:00:00,SIM,FINALIZADA,<NA>,NÃO,<NA>,0,1,NÃO
5748,79757,79757,79757,79757,79757,INCIDENTE GRAVE,-10.804722,-49.756389,LAGOA DA CONFUSÃO,TO,BRASIL,<NA>,2020-12-30,18:30:00,SIM,FINALIZADA,<NA>,NÃO,<NA>,0,1,NÃO
5749,79802,79802,79802,79802,79802,INCIDENTE,-22.81,-43.25055555555,RIO DE JANEIRO,RJ,BRASIL,SBGL,2020-12-30,00:54:00,SIM,FINALIZADA,<NA>,NÃO,<NA>,0,1,NÃO
5750,79756,79756,79756,79756,79756,INCIDENTE GRAVE,-22.507222,-54.364167,VICENTINA,MS,BRASIL,<NA>,2020-12-31,09:00:00,SIM,FINALIZADA,<NA>,NÃO,<NA>,0,1,NÃO
5751,79844,79844,79844,79844,79844,INCIDENTE,"-22,9875","-43,37",RIO DE JANEIRO,RJ,BRASIL,SBJR,2020-12-31,13:24:00,SIM,FINALIZADA,<NA>,NÃO,<NA>,0,1,NÃO

Exclui linhas duplicadas
Não haverá linhas duplicadas
PARA SALVAR NO DataFrame
df.drop_duplicates(inplace=True)

In [55]:
df.drop_duplicates()

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,40211,40211,40211,40211,40211,INCIDENTE,<NA>,<NA>,RIO DE JANEIRO,RJ,BRASIL,<NA>,2010-01-03,12:00:00,SIM,FINALIZADA,<NA>,NÃO,<NA>,0,1,NÃO
1,40349,40349,40349,40349,40349,INCIDENTE,<NA>,<NA>,BELÉM,PA,BRASIL,SBBE,2010-01-03,11:05:00,SIM,FINALIZADA,<NA>,NÃO,<NA>,0,1,NÃO
2,40351,40351,40351,40351,40351,INCIDENTE,<NA>,<NA>,RIO DE JANEIRO,RJ,BRASIL,SBRJ,2010-01-03,03:00:00,SIM,FINALIZADA,<NA>,NÃO,<NA>,0,1,NÃO
3,39527,39527,39527,39527,39527,ACIDENTE,-13.1066666667,-55.9930555556,LUCAS DO RIO VERDE,MT,BRASIL,<NA>,2010-01-04,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,0,1,NÃO
4,40324,40324,40324,40324,40324,INCIDENTE,<NA>,<NA>,PELOTAS,RS,BRASIL,SBPK,2010-01-05,19:25:00,SIM,FINALIZADA,<NA>,NÃO,<NA>,0,1,NÃO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5747,79804,79804,79804,79804,79804,INCIDENTE,-23.0069444444,-47.1344444444,CAMPINAS,SP,BRASIL,SBKP,2020-12-29,19:00:00,SIM,FINALIZADA,<NA>,NÃO,<NA>,0,1,NÃO
5748,79757,79757,79757,79757,79757,INCIDENTE GRAVE,-10.804722,-49.756389,LAGOA DA CONFUSÃO,TO,BRASIL,<NA>,2020-12-30,18:30:00,SIM,FINALIZADA,<NA>,NÃO,<NA>,0,1,NÃO
5749,79802,79802,79802,79802,79802,INCIDENTE,-22.81,-43.25055555555,RIO DE JANEIRO,RJ,BRASIL,SBGL,2020-12-30,00:54:00,SIM,FINALIZADA,<NA>,NÃO,<NA>,0,1,NÃO
5750,79756,79756,79756,79756,79756,INCIDENTE GRAVE,-22.507222,-54.364167,VICENTINA,MS,BRASIL,<NA>,2020-12-31,09:00:00,SIM,FINALIZADA,<NA>,NÃO,<NA>,0,1,NÃO
5751,79844,79844,79844,79844,79844,INCIDENTE,"-22,9875","-43,37",RIO DE JANEIRO,RJ,BRASIL,SBJR,2020-12-31,13:24:00,SIM,FINALIZADA,<NA>,NÃO,<NA>,0,1,NÃO

Missing Values = Dados não informados (NA) DO PANDAS
Também é tratado com outro classificador
NAM not anumeric utilizando a bivlioteca numpy e atribui pelo numpy o NAM num dado não informado
----------------------------------------
Dado outlayer - extrapola uma média que temos